// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbnOr7gL6J_Fi_IEahjJqW5hd29xjULj0',
    appId: '1:1036166164305:web:38d192ed8fce7ab5666d70',
    messagingSenderId: '1036166164305',
    projectId: 'studysphere-3785f',
    authDomain: 'studysphere-3785f.firebaseapp.com',
    storageBucket: 'studysphere-3785f.firebasestorage.app',
    measurementId: 'G-HXPF98FZV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBiDLVLRwDayHoy0el60_xsTVuP2QnaeI',
    appId: '1:1036166164305:android:e21271b1b67cef94666d70',
    messagingSenderId: '1036166164305',
    projectId: 'studysphere-3785f',
    storageBucket: 'studysphere-3785f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkalaps2OEGnPYRQ9vABpwFGxaPH9kmJA',
    appId: '1:1036166164305:ios:d3242cea6f9a6b45666d70',
    messagingSenderId: '1036166164305',
    projectId: 'studysphere-3785f',
    storageBucket: 'studysphere-3785f.firebasestorage.app',
    iosBundleId: 'com.example.studysphereApp',
  );
}
